version: '3.8'

networks:
  notif_net:

services:
  broker:
    image: redis
    container_name: notification_broker
    ports:
      - 6379:6379
    depends_on:
      - db
    networks:
      - notif_net

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: notification_web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - notif_net

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: notification_worker
    command: bash -c "cd src/ && celery -A config.celery worker -l INFO && celery -A config.celery beat --loglevel=info"
    volumes:
      - .:/app
    ports: []
    env_file:
      - .env
    depends_on:
      - db
      - broker
    networks:
      - notif_net

  db:
    image: postgres:15
    container_name: notification_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=notif
      - POSTGRES_PASSWORD=notif
      - POSTGRES_DB=notif
    networks:
      - notif_net

volumes:
  postgres_data:
