version: '3.8'

networks:
  notif_net:

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: notification_web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - notif_net

  db:
    image: postgres:15
    container_name: notification_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=notif
      - POSTGRES_PASSWORD=notif
      - POSTGRES_DB=notif
    networks:
      - notif_net

volumes:
  postgres_data:
